[package]
name = "penumbra-proof-setup"
version = {workspace = true}
edition = {workspace = true}

[[bench]]
name = "all"
harness = false


[features]
default = []
parallel = [
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-groth16/parallel",
    "decaf377/parallel",
    "rayon",
    "penumbra-shielded-pool/parallel",
]

[dependencies]
anyhow = {workspace = true}
ark-ec = {workspace = true, default-features = false}
ark-ff = {workspace = true, default-features = false}
ark-groth16 = {workspace = true, default-features = false}
ark-poly = { version = "0.4.2", default_features = false }
ark-relations = {workspace = true}
ark-serialize = {workspace = true}
blake2b_simd = {workspace = true}
decaf377 = {workspace = true, default-features = false}
penumbra-dex = {workspace = true}
penumbra-governance = {workspace = true}
penumbra-proof-params = {workspace = true}
penumbra-proto = {workspace = true}
penumbra-shielded-pool = {workspace = true}
penumbra-stake = {workspace = true, features = ["component"]}
rand_core = {workspace = true, features = ["getrandom"]}
rayon = { version = "1.8.0", optional = true }

[dev-dependencies]
ark-r1cs-std = {workspace = true}
ark-snark = {workspace = true}
criterion = {workspace = true, features = ["html_reports"]}
penumbra-dex = {workspace = true}
penumbra-proof-params = {workspace = true}
rand_chacha = {workspace = true}
