[package]
name = "penumbra-grpc-server"
authors.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow                 = { workspace = true }
penumbra-app           = { workspace = true }
penumbra-compact-block = { workspace = true }
penumbra-proto         = { workspace = true }
cnidarium              = { workspace = true, features = ["rpc"] }
penumbra-ibc           = { workspace = true, features = ["rpc"] }
tracing                = { workspace = true }
tonic                  = { workspace = true }
tonic-web              = { workspace = true }
tonic-reflection       = { workspace = true }
penumbra-fee           = { workspace = true }
penumbra-governance    = { workspace = true }
penumbra-sct           = { workspace = true }
penumbra-shielded-pool = { workspace = true }
penumbra-stake         = { workspace = true }
penumbra-tower-trace   = { workspace = true }
ibc-proto              = { workspace = true }

# XXX(kate): make this a workspace crate later.
penumbra-tendermint-proxy = { path = "../util/tendermint-proxy" }
