# TODO(kate): this is temporarily being enabled on pull requests so that we
# can verify that #4358 fixes problems in the summoner smoke test.
name: Summoner smoke Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke_test:
    runs-on: buildjet-16vcpu-ubuntu-2204
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment: smoke-test
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Load rust cache
        uses: astriaorg/buildjet-rust-cache@v2.5.1

      - name: Install cometbft binary
        run: ./deployments/scripts/install-cometbft

      - name: Run e2e test of summoner
        run: |
          export PATH="$HOME/bin:$PATH"
          ./deployments/scripts/smoke-summoner.sh
